# Generated by Django 3.2.7 on 2021-11-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desciption', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
